### ISSUE TITLE
Cannot load on latest Pharo 9 image DNU: ToolRegistry >> registerDebugger:withRank:

### ISSUE THREAD

**Issue by VincentBlondeau** [pharo-project/largeImages#2]
```
TKTDebugger class >> registerToolsOn: aToolRegistry
	aToolRegistry
		registerDebugger: self
		withRank: 60
```
registerDebugger:withRank: included in the GT-Tools has been removed without deprecation. I'm not sure how it should be handled instead.

**Comment by tesonep** [comment]
I changed the loading of Taskit not to be included, as the required elements are already in the image.
