### ISSUE TITLE
Evaluate the possibility to disable/remove optimized tries in Aleph

### ISSUE THREAD

**Issue by fedemennite** [pharo-project/largeImages#3]
Our standard Pharo 9 image is at about 1.5Gb of memory footprint without Aleph indexes. It gets to 3.8GB with the indexes fully built.
To my understanding (please correct me if I'm wrong) the trie based indexes are used only by the Spotter search while for any other navigation use or code autocompletion, the hash based indexes are enough.
My current estimation for hash based indexes is that they would only make the memory footprint to grow to 1.9GB.
I didn't do a full test yet but the GC performance seems to get relevant performance benefits with a smaller footprint.
We are evaluating the possibility to accept the reduced spotter performance if we can avoid to keep optimized tries instantiated.
Besides the single image GC performance, our other concern here is running parallel drone images to execute our testsuite.
If the whole indexing could be released in the drone images startup, we could avoid general GC performance demands while also reducing the required the memory footprint to run all the worker images instances.

Concluding:
- could the optimized trie usage be made optional?
- could the whole indexes cache made releasable on demand?

**Comment by tesonep** [comment]
I have added 
```
AlpIndexManager deactivate
```
That not only will deactivate the update but also discarding the indexes.
It can be later activated by using 

```
AlpIndexManager activate
```
